#include "../ReportPopup.hpp"

#include <argon/argon.hpp>

#include <Geode/Geode.hpp>

#include <Geode/ui/GeodeUI.hpp>
#include <Geode/ui/MDTextArea.hpp>

#include <Geode/utils/async.hpp>

using namespace geode::prelude;
using namespace cw::ads;

struct ReportPopup::Impl final {
    Ad ad;

    TextInput* descInput = nullptr;

    std::string userId = "";
    std::string description = "";

    async::TaskHolder<web::WebResponse> listener;
};

ReportPopup::ReportPopup() : m_impl(std::make_unique<Impl>()) {};
ReportPopup::~ReportPopup() {};

bool ReportPopup::init(Ad ad) {
    m_impl->ad = std::move(ad);

    if (!Popup::init(300.f, 200.f, "geode.loader/GE_square03.png")) return false;

    setID("report"_spr);
    setTitle("Report this ad?");
    setCloseButtonSpr(CircleButtonSprite::createWithSpriteFrameName("geode.loader/close.png", 0.875f, CircleBaseColor::DarkAqua, CircleBaseSize::Small));

    m_impl->descInput = TextInput::create(260.f, "Report Reason...", "chatFont.fnt");
    m_impl->descInput->setID("description-input");
    m_impl->descInput->setPosition({m_mainLayer->getScaledContentWidth() / 2, m_mainLayer->getScaledContentHeight() - 50});

    if (!m_impl->description.empty()) m_impl->descInput->setString(m_impl->description);

    m_mainLayer->addChild(m_impl->descInput);

    auto submitButtonSprite = ButtonSprite::create("Submit Report", 0, false, "goldFont.fnt", "geode.loader/GE_button_05.png", 0.f, 1.f);

    auto submitSpinner = LoadingSpinner::create(submitButtonSprite->getScaledContentHeight());
    submitSpinner->setVisible(false);

    auto submitButton = Button::createWithNode(
        submitButtonSprite,
        [this, submitSpinner](Button* sender) {
            submitSpinner->setVisible(true);
            sender->setVisible(false);

            onSubmitButton(sender, submitSpinner);
        });
    submitButton->setID("submit-report-btn");
    submitButton->setScale(0.875f);

    m_mainLayer->addChildAtPosition(submitButton, Anchor::Bottom);

    submitSpinner->setPosition(submitButton->getPosition());

    m_mainLayer->addChild(submitSpinner, 1);

    auto textArea = MDTextArea::create(
        "**Make sure to report this advertisement if you believe it violates the rules below.**\n\n"
        "1. No inappropriate content or excessive swearing\n"
        "2. No ads directly promoting content outside of Geometry Dash.\n"
        "3. Do not promote unsafe practices.\n"
        "4. Ads mostly generated by AI are not allowed.\n"
        "5. Artificially inflating engagement statistics is strictly prohibited.\n\n"
        "<cr>Multiple false reports will likely lead to your account getting blacklisted.</c>",
        {260.f, 100.f});
    textArea->setPosition({m_mainLayer->getScaledContentWidth() / 2, m_mainLayer->getScaledContentHeight() / 2 - 25});

    m_mainLayer->addChild(textArea);

    return true;
};

void ReportPopup::onSubmitButton(Button* sender, LoadingSpinner* spinner) {
    if (!m_impl->descInput) return;

    auto upopup = UploadActionPopup::create(nullptr, "Submitting report...");
    upopup->show();

    std::string desc = m_impl->descInput->getString();

    if (desc.size() < 10) {
        upopup->showFailMessage("Report reason is too short");

        sender->setVisible(true);
        spinner->setVisible(false);

        return;
    };

    async::spawn(
        argon::startAuth(),
        [self = WeakRef(this), btn = WeakRef(sender), btnLoad = WeakRef(spinner), desc = std::move(desc), upopup = WeakRef(upopup)](Result<std::string> res) {
            if (auto s = self.lock()) {
                if (res.isErr()) {
                    log::warn("Auth failed: {}", std::move(res).unwrapErr());
                    if (auto up = upopup.lock()) up->showFailMessage("Failed to authorize with Argon");

                    return;
                };

                auto token = std::move(res).unwrap();
                Mod::get()->setSavedValue<std::string>("authtoken", token);
                log::debug("Token: {}", token);

                auto reportReq = web::WebRequest();
                reportReq.userAgent("PlayerAdvertisements/1.2");
                reportReq.timeout(std::chrono::seconds(15));

                matjson::Value body = matjson::Value();

                body["ad_id"] = s->m_impl->ad.getID();
                body["account_id"] = GJAccountManager::sharedState()->m_accountID;
                body["description"] = std::move(desc);
                body["authtoken"] = std::move(token);

                reportReq.bodyJSON(body);

                async::spawn(
                    reportReq.post("https://ads.cheeseworks.gay/api/report"),
                    [self, upopup, btn, btnLoad](web::WebResponse res) {
                        if (auto s = self.lock()) {
                            if (res.ok()) {
                                s->onClose(nullptr);
                                if (auto up = upopup.lock()) up->showSuccessMessage("Report submitted successfully!");
                            } else {
                                if (auto up = upopup.lock()) up->showFailMessage(res.code() == 403 ? "You've been banned from reporting ads." : "Failed to send report!");
                            };

                            if (auto b = btn.lock()) b->setVisible(true);
                            if (auto bLoad = btnLoad.lock()) bLoad->setVisible(false);
                        };
                    });
            };
        });
};

ReportPopup* ReportPopup::create(Ad ad) {
    auto ret = new ReportPopup();
    if (ret->init(std::move(ad))) {
        ret->autorelease();
        return ret;
    };

    delete ret;
    return nullptr;
};